// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bitrise-io/go-utils/v2/command"
	mock "github.com/stretchr/testify/mock"
)

// NewRubyCommandFactory creates a new instance of RubyCommandFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRubyCommandFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *RubyCommandFactory {
	mock := &RubyCommandFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RubyCommandFactory is an autogenerated mock type for the CommandFactory type
type RubyCommandFactory struct {
	mock.Mock
}

type RubyCommandFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *RubyCommandFactory) EXPECT() *RubyCommandFactory_Expecter {
	return &RubyCommandFactory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RubyCommandFactory
func (_mock *RubyCommandFactory) Create(name string, args []string, opts *command.Opts) command.Command {
	ret := _mock.Called(name, args, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 command.Command
	if returnFunc, ok := ret.Get(0).(func(string, []string, *command.Opts) command.Command); ok {
		r0 = returnFunc(name, args, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.Command)
		}
	}
	return r0
}

// RubyCommandFactory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RubyCommandFactory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
//   - args []string
//   - opts *command.Opts
func (_e *RubyCommandFactory_Expecter) Create(name interface{}, args interface{}, opts interface{}) *RubyCommandFactory_Create_Call {
	return &RubyCommandFactory_Create_Call{Call: _e.mock.On("Create", name, args, opts)}
}

func (_c *RubyCommandFactory_Create_Call) Run(run func(name string, args []string, opts *command.Opts)) *RubyCommandFactory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *command.Opts
		if args[2] != nil {
			arg2 = args[2].(*command.Opts)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RubyCommandFactory_Create_Call) Return(command1 command.Command) *RubyCommandFactory_Create_Call {
	_c.Call.Return(command1)
	return _c
}

func (_c *RubyCommandFactory_Create_Call) RunAndReturn(run func(name string, args []string, opts *command.Opts) command.Command) *RubyCommandFactory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBundleExec provides a mock function for the type RubyCommandFactory
func (_mock *RubyCommandFactory) CreateBundleExec(name string, args []string, bundlerVersion string, opts *command.Opts) command.Command {
	ret := _mock.Called(name, args, bundlerVersion, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateBundleExec")
	}

	var r0 command.Command
	if returnFunc, ok := ret.Get(0).(func(string, []string, string, *command.Opts) command.Command); ok {
		r0 = returnFunc(name, args, bundlerVersion, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.Command)
		}
	}
	return r0
}

// RubyCommandFactory_CreateBundleExec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBundleExec'
type RubyCommandFactory_CreateBundleExec_Call struct {
	*mock.Call
}

// CreateBundleExec is a helper method to define mock.On call
//   - name string
//   - args []string
//   - bundlerVersion string
//   - opts *command.Opts
func (_e *RubyCommandFactory_Expecter) CreateBundleExec(name interface{}, args interface{}, bundlerVersion interface{}, opts interface{}) *RubyCommandFactory_CreateBundleExec_Call {
	return &RubyCommandFactory_CreateBundleExec_Call{Call: _e.mock.On("CreateBundleExec", name, args, bundlerVersion, opts)}
}

func (_c *RubyCommandFactory_CreateBundleExec_Call) Run(run func(name string, args []string, bundlerVersion string, opts *command.Opts)) *RubyCommandFactory_CreateBundleExec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *command.Opts
		if args[3] != nil {
			arg3 = args[3].(*command.Opts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *RubyCommandFactory_CreateBundleExec_Call) Return(command1 command.Command) *RubyCommandFactory_CreateBundleExec_Call {
	_c.Call.Return(command1)
	return _c
}

func (_c *RubyCommandFactory_CreateBundleExec_Call) RunAndReturn(run func(name string, args []string, bundlerVersion string, opts *command.Opts) command.Command) *RubyCommandFactory_CreateBundleExec_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBundleInstall provides a mock function for the type RubyCommandFactory
func (_mock *RubyCommandFactory) CreateBundleInstall(bundlerVersion string, opts *command.Opts) command.Command {
	ret := _mock.Called(bundlerVersion, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateBundleInstall")
	}

	var r0 command.Command
	if returnFunc, ok := ret.Get(0).(func(string, *command.Opts) command.Command); ok {
		r0 = returnFunc(bundlerVersion, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.Command)
		}
	}
	return r0
}

// RubyCommandFactory_CreateBundleInstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBundleInstall'
type RubyCommandFactory_CreateBundleInstall_Call struct {
	*mock.Call
}

// CreateBundleInstall is a helper method to define mock.On call
//   - bundlerVersion string
//   - opts *command.Opts
func (_e *RubyCommandFactory_Expecter) CreateBundleInstall(bundlerVersion interface{}, opts interface{}) *RubyCommandFactory_CreateBundleInstall_Call {
	return &RubyCommandFactory_CreateBundleInstall_Call{Call: _e.mock.On("CreateBundleInstall", bundlerVersion, opts)}
}

func (_c *RubyCommandFactory_CreateBundleInstall_Call) Run(run func(bundlerVersion string, opts *command.Opts)) *RubyCommandFactory_CreateBundleInstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *command.Opts
		if args[1] != nil {
			arg1 = args[1].(*command.Opts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RubyCommandFactory_CreateBundleInstall_Call) Return(command1 command.Command) *RubyCommandFactory_CreateBundleInstall_Call {
	_c.Call.Return(command1)
	return _c
}

func (_c *RubyCommandFactory_CreateBundleInstall_Call) RunAndReturn(run func(bundlerVersion string, opts *command.Opts) command.Command) *RubyCommandFactory_CreateBundleInstall_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGemInstall provides a mock function for the type RubyCommandFactory
func (_mock *RubyCommandFactory) CreateGemInstall(gem string, version string, enablePrerelease bool, force bool, opts *command.Opts) []command.Command {
	ret := _mock.Called(gem, version, enablePrerelease, force, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateGemInstall")
	}

	var r0 []command.Command
	if returnFunc, ok := ret.Get(0).(func(string, string, bool, bool, *command.Opts) []command.Command); ok {
		r0 = returnFunc(gem, version, enablePrerelease, force, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.Command)
		}
	}
	return r0
}

// RubyCommandFactory_CreateGemInstall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGemInstall'
type RubyCommandFactory_CreateGemInstall_Call struct {
	*mock.Call
}

// CreateGemInstall is a helper method to define mock.On call
//   - gem string
//   - version string
//   - enablePrerelease bool
//   - force bool
//   - opts *command.Opts
func (_e *RubyCommandFactory_Expecter) CreateGemInstall(gem interface{}, version interface{}, enablePrerelease interface{}, force interface{}, opts interface{}) *RubyCommandFactory_CreateGemInstall_Call {
	return &RubyCommandFactory_CreateGemInstall_Call{Call: _e.mock.On("CreateGemInstall", gem, version, enablePrerelease, force, opts)}
}

func (_c *RubyCommandFactory_CreateGemInstall_Call) Run(run func(gem string, version string, enablePrerelease bool, force bool, opts *command.Opts)) *RubyCommandFactory_CreateGemInstall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 *command.Opts
		if args[4] != nil {
			arg4 = args[4].(*command.Opts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *RubyCommandFactory_CreateGemInstall_Call) Return(commands []command.Command) *RubyCommandFactory_CreateGemInstall_Call {
	_c.Call.Return(commands)
	return _c
}

func (_c *RubyCommandFactory_CreateGemInstall_Call) RunAndReturn(run func(gem string, version string, enablePrerelease bool, force bool, opts *command.Opts) []command.Command) *RubyCommandFactory_CreateGemInstall_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGemUpdate provides a mock function for the type RubyCommandFactory
func (_mock *RubyCommandFactory) CreateGemUpdate(gem string, opts *command.Opts) []command.Command {
	ret := _mock.Called(gem, opts)

	if len(ret) == 0 {
		panic("no return value specified for CreateGemUpdate")
	}

	var r0 []command.Command
	if returnFunc, ok := ret.Get(0).(func(string, *command.Opts) []command.Command); ok {
		r0 = returnFunc(gem, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]command.Command)
		}
	}
	return r0
}

// RubyCommandFactory_CreateGemUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGemUpdate'
type RubyCommandFactory_CreateGemUpdate_Call struct {
	*mock.Call
}

// CreateGemUpdate is a helper method to define mock.On call
//   - gem string
//   - opts *command.Opts
func (_e *RubyCommandFactory_Expecter) CreateGemUpdate(gem interface{}, opts interface{}) *RubyCommandFactory_CreateGemUpdate_Call {
	return &RubyCommandFactory_CreateGemUpdate_Call{Call: _e.mock.On("CreateGemUpdate", gem, opts)}
}

func (_c *RubyCommandFactory_CreateGemUpdate_Call) Run(run func(gem string, opts *command.Opts)) *RubyCommandFactory_CreateGemUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *command.Opts
		if args[1] != nil {
			arg1 = args[1].(*command.Opts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RubyCommandFactory_CreateGemUpdate_Call) Return(commands []command.Command) *RubyCommandFactory_CreateGemUpdate_Call {
	_c.Call.Return(commands)
	return _c
}

func (_c *RubyCommandFactory_CreateGemUpdate_Call) RunAndReturn(run func(gem string, opts *command.Opts) []command.Command) *RubyCommandFactory_CreateGemUpdate_Call {
	_c.Call.Return(run)
	return _c
}
